---
title: "QUARTO-demo"
author: "team-datasommer"
theme: minty
toc: true
toc-location: left
number-sections: true
highlight-style: pygments
format:
  html:
    embed-resources: true
    page-layout: article
    code-fold: true
    grid:
      sidebar-width: 150px
      body-width: 800px
      margin-width: 100px
    other-links: 
      - text: Antall arbeidssøkere datasett
        href: https://data.norge.no/datasets/a56d54a2-f57b-35e9-a59d-4d0c87e69664
jupyter: python3
---

## Intro til datafortellinger
I NAV bruker vi datafortellinger for å formidle innsikt vi får ut av dataene våre.

### Hva er en datafortelling?

Datafortellinger er nettsider som kan inneholde interaktive elementer som grafer og kode, sammen med forklarende tekst. Når en datafortelling er ferdig og klar til å deles med andre i NAV, kan den publiseres på [datamarkedsplassen](https://data.ansatt.nav.no/) og dermed bli tilgjengelig for andre. Datafortellinger gjør det enkelt å dele og tilgjengeliggjøre dine funn på en brukervennlig måte. Det finnes mange enkle verktøy for å produsere nettsider som kan publiseres som datafortellinger, men det vanligste er programmet her i NAV [Quarto](https://quarto.org/).

Her kan dere finne noen fine eksempler på ulike datafortelleinger laget av andre i NAV: 

Dashboard: [Hvor er damene?](https://data.ansatt.nav.no/story/7ea943c9-ae07-4d75-9b65-d775c05230dc/make_dashboard.html)

Article: [Veileder for kunnskapsbaserte språkmodeller](https://data.ansatt.nav.no/story/58aa330c-3a72-470e-926f-22e029719879/bakgrunn.html)


#### Hva er Quarto?
Quarto kan produsere nettsider, dashboards og presentasjoner. Quarto .qdm filer inneholder en kombinasjon av  markdown og kodesnutter; Du kan i disse filene skrive kode for å lage dynamisk innhold i Python, R, Julia eller Observable.  Quarto kan også integreres med VS Code ved hjelp av en extension.

For å laste ned Quarto kan dere følge denne [lenken](https://quarto.org/docs/download/tarball.html).


Hvis dere ønsker mer informasjon om datafortellinger og quarto kan dere lese på KNADA docs, som dere finner her: [KNADA docs](https://docs.knada.io/analyse/datafortellinger/).


## Demo

NAV publiserer offisiell statistikk på nav.no om antall arbeidsledige og arbeidssøkere. For denne demoen har vi valgt å bruke data om antall arbeidssøkere etter yrke og år. Du kan lese ler om selve datasettet [her](https://data.norge.no/datasets/a56d54a2-f57b-35e9-a59d-4d0c87e69664). Arbeidssøkere er personer som søker arbeid ved NAV og som er tilgjengelige for det arbeidet som søkes. Hovedregelen er at man anses som arbeidssøker hos NAV hvis man har meldt seg eller fornyet meldingen i løpet av de to siste ukene. 

 Datasettet inneholder statistikk om arbeidssøkere fordelt på yrkesbakgrunn, med mer detaljerte yrkesopplysninger enn det som er publisert på nav.no. NAV benytter den internasjonale standarden for yrkesklassifisering, International Standard Classification of Occupations (ISCO) som ILO har utarbeidet. For klassifisering av yrker benyttes ISCO-08 (før januar 2012 ISCO-88 og før mai 2001 ISCO-58). 

```{python}
#| label: fig-antall
#| fig-cap: "Antall arbeidssokere fra 2002 til 2017"

import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from hent_data import hent_data

df = hent_data()
hist = px.histogram(df, x = 'aar', y = 'antall_arbeidssokere')
hist.update_xaxes(tickangle=90, tickmode = 'linear')
hist.update_layout(bargap = 0.2)
hist.show()

```

@fig-antall viser en oversikt over antall arbeidssøkere fordelt per år, for 2002 til 2017. 

```{python}
#| label: arbeidsøkere-fig
#| fig-cap: "Histogram over antall arbeidssøkere innen hver yrkeskategori. Visualiseringen inneholder tall fra $01.01.2002$ - $31.12.2017$."
#| 
fig = px.histogram(df, x= 'aar', y = 'antall_arbeidssokere', color = 'yrke_grovgruppe')
fig.update_xaxes(tickangle=90, tickmode = 'linear')
fig.update_layout(bargap = 0.2)
fig.show()
```



## Oppgave

La oss si at vi ønsker å se videre på hvordan fordelingen ser ut innen yrkesgruppen Helse, pleie og omsorg. Dere skal prøve å lage deres egen datafortelling basert på datasettet om antall arbeidssøkere. Dere må da hente inn datasettet fra GCP, lage et plott og registrere datafortellingen i datamarkedsplassen. HVis dere ønsker, kan dere ta utgangspunkt i hvordan data er hentet og visualisert i denne datafrortellingen. Oppgaven er altså å:

* Hente inn data fra gcp
* Lage en ny datafortelling med et plott over antall arbeidssøkere fra 2002 til 2017 innen yrke-grovgruppen Helse, pleie og omsorg
* Registre ny datafortelling på datamarkedsplassen


Dere finner en guide til hvordan man registrerer og laster opp en datafortelilng til datamarkedsplassen [her](https://docs.knada.io/analyse/datafortellinger/#lage-datafortelling).